zmap/zgrab

README.md

Add to build instructions and requirements

---

ztools/ztls/ztls_json.go
ztools/ztls/ztls_names.go

This makes it possible to retrieve the name without marshalling the struct to JSON.
I need it because I use zgrab with my own worker.

Extract String() method from MarshalJSON

---

ztools/processing/input.go

It is more convenient in this place.

Use wait groups instead of pipes

---

ztools/ztls/ztls_names.go

I need these to get the version and cipher suite as byte array in my application.

Add Bytes() to CipherSuite and TLSVersion

---

main.go
zgrab_schema.py
zlib/config.go
zlib/conn.go
zlib/grabber.go
zlib/zgrab.go
ztools/bacnet/common.go
ztools/bacnet/log.go
ztools/bacnet/messages.go
ztools/bacnet/messages_test.go
ztools/bacnet/objects.go
ztools/bacnet/objects_test.go
ztools/bacnet/query.go

Start basic definitions of constants and message types.
Not ready to merge yet. Will fix #83.

Add BACNet package

---

ztools/http/header.go

Length-limit headers to < 8K

---

main.go

Remove --udp

---

ztools/http/response.go

Revert "add alt_svc and alternate_protocol as known headers"

---

zgrab_schema.py
ztools/http/response.go

Second attempt at resolving: https://github.com/zmap/zgrab/issues/111. This time with schema changes!

add alt svc and alt protocol http headers + schema

---

ztools/x509/pkix/json.go

revert the small change that broke 1.5 support

---

zlib/grabber.go
zlib/grabber_test.go

Properly set SNI when redirecting from HTTP to HTTPS, and added a functional test that handles redirects.

set sni properly on https redirect + testing

---

ztools/x509/json.go
ztools/x509/x509.go

for percert/cert linking to address #143.

Added a tbs fingerprint without poison extension 

---

ztools/x509/cert_pool.go
ztools/x509/json.go

Cert perspectives fix

---

zlib/grabber.go

I believe we were leaking memory on errored connections.

Defer resp.Body.Close() in HTTP

---

ztools/x509/extensions.go
ztools/x509/extensions_test.go
ztools/x509/json.go

This is a schema-breaking change.

Add CIDR to X.509 IP name constraints

---

zcertificate/main.go
ztools/x509/extensions.go
ztools/x509/x509.go

Revert "certpolicy output"

---

ztools/ztls/common.go

Currently, all servers are required to support ECC curves for all handshakes (even if non-ECDHE). If CurvePreferences is left empty, then it will default to CurveP256, CurveP384, and CurveP521. This is misleading when dealing with configurations where curves were intentionally left unset, but 3 are supported.

Add ExplicitCurvePreferences to allow no supported ECC curves.

---

ztools/http/client.go

Memory Leak in #187 was caused by http redirects.
The redirect response bodies weren't being properly closed causing the goroutines to remain open. 
Changed variable names to close correct response bodies.

Close Response Body

---

zlib/grabber.go

Resolves #298
Thoughts @dadrian?

Fix domain bug

---

Gopkg.lock
Gopkg.toml
vendor/github.com/prometheus/procfs/fixtures.ttar
vendor/github.com/prometheus/procfs/ttar
vendor/golang.org/x/sys/unix/syscall_unix.go

* Updated Gopkg.toml to use zcrypto@release/0.1 (peg it to pre-https://github.com/zmap/zcrypto/pull/108)
* Ran `dep ensure -update`

change to zcrypto@release/0.1

---

zgrab_schema.py

For https://github.com/zmap/zcrypto/pull/119 (`dep ensure -update` to pull down the newest version is in a separate PR).

add digest to ssl server key exchange schema

---

ztools/xssh/kex.go

zgrab1 companion to https://github.com/zmap/zgrab2/pull/130

don't set ecdh kex fields unless they are actually going to be used

---

Gopkg.lock
Gopkg.toml
vendor/github.com/zmap/zcrypto/ct/x509/root_darwin.go
vendor/github.com/zmap/zcrypto/x509/root_cgo_darwin.go
vendor/golang.org/x/net/http2/hpack/encode.go
ztools/zct/x509/root_darwin.go

* Pin version of golang.org/x/net (master removed httplex)
* Fix CFDataRef build errors

Darwin build fixes
