ztools/ztls/ztls_json.go, ztools/ztls/ztls_names.go
Reverts zmap/zgrab#39. 
Previous commit was resulting in corrupted names. This is what I get for testing after merging.
=> Revert "Extract String() method from MarshalJSON"

ztools/x509/x509.go
According to https://tools.ietf.org/html/rfc5280#section-4.1.2.2
```
Non-conforming CAs may issue certificates with serial numbers
that are negative or zero.  Certificate users SHOULD be prepared to
gracefully handle such certificates.
```
This issue is also addressed by https://github.com/golang/go/issues/8265
From 208314 hosts 662 were affected by this problem. Some examples:
* 93.57.50.24
* 123.100.249.85
* 202.43.34.79
=> Gracefully handle negative serial numbers

ztools/ztls/ztls_json.go, ztools/ztls/ztls_names.go
This makes it possible to retrieve the name without marshalling the struct to JSON.
`x.String()` works better than `string(x)`
=> Extract String() method from MarshalJSON [fixed]

.test-cover.sh, .travis.yml, README.md
This pull request also updates Go from 1.4 to 1.4.2.
You need to connect your github Account with Coveralls.io.
The result looks like this: https://coveralls.io/github/corny/zgrab
=> Add coveralls.io to display test coverage

zlib/http.go
This should fix the following error. @zzma, can you double check?
```
panic: interface conversion: interface is nil, not string
goroutine 505 [running]:
github.com/zmap/zgrab/zlib.HTTPResponse.canRedirectWithConn(0x1, 0x1, 0x12d, 0xc20aff1cc0, 0x1e, 0xc2093fd1a0, 0xc20bae4000, 0x27a4, 0xc20aff1ee0, 0x20, ...)
/var/search/tmp/gopath_vab9w56a/src/github.com/zmap/zgrab/zlib/http.go:161 +0x104
github.com/zmap/zgrab/zlib.(*Conn).doHTTP(0xc20da33a40, 0xb36408, 0x0, 0x0)
/var/search/tmp/gopath_vab9w56a/src/github.com/zmap/zgrab/zlib/conn.go:333 +0x207
github.com/zmap/zgrab/zlib.(*Conn).HTTP(0xc20da33a40, 0xb36408, 0x0, 0x0)
/var/search/tmp/gopath_vab9w56a/src/github.com/zmap/zgrab/zlib/conn.go:206 +0x8f
github.com/zmap/zgrab/zlib.func·002(0xc20da33a40, 0x0, 0x0) …
```
=> Fix nil interface conversion error

zgrab_schema.py, zlib/conn.go, zlib/http.go, zlib/zgrab.go
Minor tweak to HTTP redirects. Previously we were storing the initial HTTP response (aka a 300 response) as the top-level HTTPRequestResponse.response, and the terminal 200 response was being stored as the last element of HTTPRequestResponse.redirect_responses. I've change it so that HTTPRequestResponse.response now contains the terminal response at the end of max-redirects, and moved the initial http response to be the first item of HTTPRequestResponse.redirect_responses.
One concern I have is that the requests and responses are misaligned. HTTPRequestResponse.request does not directly return HTTPRequestResponse.response. Also the HTTPRequestResponse.redirect_requests and HTTPRequestResponse.redirect_responses are off-by-one. Are we okay with this?
=> use terminal response as top level response

zlib/http.go, zlib/processing.go, ztools/util/util.go
addressing issue: https://github.com/zmap/zgrab/issues/88
@dadrian
Make sure we also check that the TLD matches, when doing redirect-ability checking.
=> strict host matching for redirect urls

zlib/conn.go
stop writing to stderr. I didn't want to have to pass the config ErrorLog all the way down, so I created a new error that gets sent up the pipeline and logged properly.
=> don't zlog.Error to stderr

main.go, zgrab_schema.py, zlib/config.go, zlib/conn.go, zlib/grabber.go, ztools/ztls/common.go, ztools/ztls/handshake_client.go, ztools/ztls/ztls_handshake.go
The --tls-session-ticket-ext flag adds the Session Ticket extension
support to TLS Client Hello. If the server sends a New Session Ticket
payload, then the ticket value is extracted and saved in JSON output.
=> Gather TLS Session Tickets

ztools/http/header.go, ztools/http/response.go
Reverts to the old behaviour of only parsing a white-listed set of known headers. All other headers go under the "unknown" header field.
Example query:
`echo "88.85.84.122" | zgrab --port 80 --http="/" --http-max-redirects=2`
Result:
```
{
"ip": "88.85.84.122",
"timestamp": "2016-03-22T10:15:35-05:00",
"data": {
"http": {
"response": {
"status_line": "200 OK",
"status_code": 200,
"protocol": {
"name": "HTTP\/1.1",
"major": 1,
"minor": 1
},
"headers": {
"cache_control": [
"no-cache, must-revalidate"
],
"connection": [
"keep-alive"
],
"content_type": [
"text\/html; charset=\"UTF-8\""
],
"expires": [
"Mon, 26 Jul 1997 05:00:00 GMT"
],
"last_modified": [
"Tue, 22 Mar 2016 15:15:11 GMT"
],
"pragma": [
"no-cache"
],
"server": [
"nginx\/1.8.0"
],
"set_cookie": [
"lang=0; …
```
=> only parse known headers

ztools/scada/siemens/s7.go
@zakird 
FYI - going to go ahead and auto-merge. While re-visiting S7 protocol, I noticed that adding this field increases the number of detected S7 devices without losing any devices that are already  being detected.
=> add pdu length field to s7 request

zlib/grabber.go
@zakird 
This seems to fix the main memory leak error and hopefully will resolve the issues we were seeing for the HTTP scans. Basically, we were caching every connection and never purging. The other thing is that we never really utilized the cache, so this change should not noticeably affect performance.
=> don't hold on to idle connections

zlib/grabber.go
Do HTTPS when --TLS flag is specified. I must have overlooked this when implementing the new HTTP stuff.
=> actually do https when --tls flag is specified

.travis.yml, ztools/ztls/cipher_suites.go
Longer term, we should vendor all of our dependencies.
Fixes #103
=> Use zmap/rc2 instead of dadrian/rc2

ztools/http/response.go
Headers for issue: https://github.com/zmap/zgrab/issues/111
Tested on google, which returns: 
```
"headers":{"alt_svc":["quic=\":443\"; ma=2592000; v=\"34,33,32,31,30,29,28,27,26,25\""],"alternate_protocol":["443:quic"],....
```
=> add alt_svc and alternate_protocol as known headers

main.go, zlib/grabber.go
@dadrian @zakird 
Need to set up the TLSConfig whenever there are redirects, in case it's a http --> https redirect. HTTPS redirects were previously using a default TLSConfig that was automatically failing on validation errors.
=> setup TLSConfig whenever redirecting

ztools/ztls/key_agreement.go
Newly introduced AugmentedECDSA broke key agreement for my code. Here's the commit, that fixed the issue
=> Convert to (x509.AugmentedECDSA), not (ecdsa.PublicKey)

ztools/x509/x509.go
Added the fields IssuerUniqueId and SubjectUniqueId as asn1.BitString values to x509.Certificate.
This allows code using this library to detect and access the optional UniqueIdentifier fields from the underlying certificate (if it has them).
=> Added fields to Certificate to expose UniqueIdentifier fields from the underlying certificate

zlib/grabber.go, ztools/http/response.go
This is for issue https://github.com/zmap/zgrab/issues/190. Instead of returning `nil` when HTTP fails, return an incomplete HTTP data object that includes TLS info. 
Before: 
```
$ echo "52.50.169.99" | ./zgrab --port 443 --tls --http="/"
{"ip":"52.50.169.99","timestamp":"2016-10-05T23:30:24Z","data":{"http":{}},"error":"Get https://52.50.169.99:443/: unexpected EOF"}
```
After:
```
$ echo "52.50.169.99" | ./zgrab --port 443 --tls --http="/"
{
"ip": "52.50.169.99",
"timestamp": "2016-10-06T08:55:49-05:00",
"data": {
"http": {
"response": {
"protocol": {
},
"request": {
"url": {
"scheme": "https",
"host": "52.50.169.99:443",
"path": "\/"
},
"method": "GET",
"headers": {
"user_agent": [
"Mozilla\/5.0 zgrab\/0.x"
]
},
"host": "52.50.169.99",
"tls_handshake": { …
```
=> return a partial response even when HTTP ultimately fails

ztools/ztls/common.go, ztools/ztls/handshake_client.go
Added functionality: explicitly set ClientRandom.
Needed for Telex-style tag(which is now used by Tapdance along with its own tag to speed things up)
=> Set ClientRandom explicitly

.travis.yml, main.go
This adds Prometheus integration via the --prometheus flag. The flags
defaults to empty. When the flag is non-empty it launches an HTTP server
at the specified endpoint (e.g. "localhost:8080"), that exposes the
Prometheus metric source API at the /metrics path.
This also updates TravisCI to download dependencies more sanely, and
bumps the version of Golang used by TravisCI to 1.7.4.
=> Add Prometheus integration, update TravisCI

ztools/ztls/handshake_messages.go
When `unmarshal`-ling ClientHellos, the `renegotiation_info` extension failed to be identified.
=> Fix renegotiation extension unmarshall

zlib/grabber.go
With inputs of the form `<IP>,<domain_name>`, and no `lookup-domain` option, the SNI extension in the ClientHellos sent by `zgrab` contained `<IP>:<port>` instead of the domain name. This is non-standard and probably unwanted behavior.
=> Fix SNI insertion

main.go, zlib/config.go, zlib/conn.go, zlib/grabber.go
This commit removes the encoding flag and associated structures as it wasn't implemented/didn't have a function. Addresses Issue #185
=> * Removed --encoding option to fix 185

main.go, summary.go
Add the cmd flags to the metadata output IOT help document scan configuration.
Output format --
```json
{
"port": 22,
"success_count": 1,
"failure_count": 0,
"total": 1,
"start_time": "2017-02-04T17:02:46-05:00",
"end_time": "2017-02-04T17:02:46-05:00",
"duration": 0,
"senders": 1000,
"timeout": 10,
"tls_version": null,
"mail_type": null,
"ca_file_name": null,
"sni_support": true,
"flags": [
"./zgrab",
"--xssh",
"--port",
"22",
"--output-file",
"output.json",
"--metadata-file",
"metadata.json"
]
}
```
=> Add command-line flags to metadata output.

main.go, zlib/config.go, zlib/conn.go, zlib/grabber.go, ztools/ztls/common.go, ztools/ztls/handshake_client.go, ztools/ztls/handshake_messages.go
This commit enables importing raw ClientHellos to be sent during the `zgrab` scans.
When providing such information with the `raw-client-hello` option, `zgrab` will only rewrite the SNI extension with the current domain name to be queried. The ClientHello contents will stay otherwise untouched (well, except for the extensions order). As a side effect, other options like `chrome-ciphers` or `tls-session-ticket` are ignored.
Main motivations behind this:
- some extensions may not be known to `zgrab`, but we might want to send them nonetheless;
- `zgrab` options do not cover every field/value to be written in the ClientHello probe. I've been using `scapy` for designing TLS messages, which is more exhaustive and flexible IMHO. (The [PR](https://github.com/secdev/scapy/pull/476) has been in …
=> Add external ClientHello support

zlib/conn.go, zlib/grabber.go
Resolves #238 
SMTP server requires Quit command as stated in RFC 5321 Section 3.1
IMAP and POP3 are both ambiguous on whether a server requires a close/quit command because a timeout could be implemented by the server. Either way, sending a quit command probably doesn't hurt.
=> Made SMTP, IMAP, and POP3 RFC Compliant

ztools/ztls/common.go
```ForceSuites``` is ambiguous and lacks description. Fix that.
=> Add missing comment for ForceSuites setting.

zcertificate/main.go, ztools/x509/extensions.go, ztools/x509/x509.go
Output of ./zcertificate:
{"raw":"MIIE+jCCA+KgAwIBAgIQZyIjammE5+m7FKjyKv530TANBgkqhkiG9w0BAQsFADBCMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMSUmFwaWRTU0wgU0hBMjU2IENBMB4XDTE2MDEyMjAwMDAwMFoXDTE3MDEyMjIzNTk1OVowgZcxCzAJBgNVBAYTAlVTMR0wGwYDVQQIDBREaXN0cmljdCBvZiBDb2x1bWJpYTETMBEGA1UEBwwKV2FzaGluZ3RvbjESMBAGA1UECgwJZmFubmllbWFlMRwwGgYDVQQLDBNpbnRlcm5ldGVuZ2luZWVyaW5nMSIwIAYDVQQDDBlzZWNvcHMtaWRldi5mYW5uaWVtYWUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2cc+jwLSRF2MI679cOzCQGoLC1X2DmA53NK0WSaUISDCTuQLTeocloKI4797bYX4RiEwh5kpinARk2SwbqjDzpHv86jELPVaMGBbgEfXtoqGcmXFEOaTw6WaroLhZEDVQW82qEXu/LeaicPyrGYeGRk1fAMDQRT+FjIdUraKGti+pkfuLVqCDYQ3WcYJyc57NE/uIOlS3MgCSxZ2kZm4CbtyMQzdDDTPi+uBMrWCL3/n8Pq/jnwjoCPxMB23jj911l8+OtPhULkd6DO0ohY5p/ABH0YNzb2hKVig5qgrBJKUZoYwpa92S6F480AFd29lgO …
=> certpolicy output

ztools/http/transport.go
This error arises when a header is incorrectly formatted or "bogus stuff". https://github.com/golang/go/issues/19895
Removing it is good because we encounter incorrectly formatted stuff quite often.
=> remove log error

zgrab_schema.py
ZSchema warns that the Short and Integer types are deprecated. This changes their usage in the XSSH schema to appropriate non-deprecated types.
=> Avoid using deprecated types in XSSH schema

zgrab_schema.py, ztools/xssh/kex.go
This matches the following parameters, from [a problematic record](https://gist.github.com/cdzombak/95244e6f5b5c0e1a5f41322309043159):
```
"parameters": {
"prime": {
"length": 2048,
"value": "///////////JD9qiIWjCNMTGYouA3BzRKQJOCIpnzHQCC76mOxObIlFKCHmONATd75UZs806QxswKwpt8l8UN0/hNW1tUcJF5IW1dmJefsb0TELppjftawv/XLb0Brft7jhr+1qJn6WunyQRfEsf5kkoZlHs5Fs9wgB8uKFjvwWY2kg2HFXTmmkWP6j9JM9fg2VdI9yjrZYcYvNWIIVSu57VKQdwlpZtZww1Tkq8mATxdGwIyhghfDKQXkYuNs474553LBgOhgObJ4Oi7Aeij7XFXfBvTFLJ3ivL9pVYFxg5lUl86pVq5RXSJhiY+gUQFXKOWoqsqmj//////////w=="
},
"server_public": {
"length": 2048,
"value": "0kz7iK25lCVUdaVm8I1itiCOd2lSYKZffrlfHFwYOLJB5P0bVrEuE7+VmXSQIcH5L4Ia/+bKQJWm4lZP5/8gB1siD/0lokrsJBz6s7vPJtCZDQCX9gsE+UU8bgQYvqn7kTfpM2w5Jc5d3uChCVsYtQ+S+ZUCXVvhW7UqETeXvOQo8TPGU60INrLMN+jyli3rqR9BxzPWxariXFWJw1/EDA …
```
=> Correct schema for XSSH DH params

zgrab_schema.py, ztools/xssh/flag.go, ztools/xssh/kex.go, ztools/xssh/kex_gex.go, ztools/xssh/log.go
The principal goal of this PR is to split up the different types of key exchanges for the XSSH grabber into separate names, to allow defining a consistent schema.
There is a little more massaging & rearranging to do to make this data show up nicely in Censys, but I propose doing that in ZTag. (I should have a follow-up PR there this afternoon.)
=> Break out XSSH key exchanges by type in JSON output 

zlib/grabber.go, zlib/grabber_test.go
For `http` zgrab requests, add an `Accept: */*` header (addresses issue #301)
=> Add Accept HTTP header

README.md, main.go, zlib/config.go, zlib/conn.go, zlib/grabber.go
This PR is connected to new functionality proposed for zcryto: https://github.com/zmap/zcrypto/pull/100
Scanning goes faster if you don't continue the TLS handshake after getting the certs, and furthermore if you don't parse the TLS Certs on the same host that scans them.  With this option you can scan more hosts faster (by moving on before completing the TLS handshake) and you can collect certificates, diff them against a store of parsed certificates, and only parse the new ones.
=> TLSCertsOnly Option

zlib/grabber.go
If there is a `panic()` while scanning a target in GrabBanner, trap it and log the target to the standard logger at the ERROR level, before re-throwing the panic.
There is no place place that intentionally panics, so I have been testing by adding a panic() call to e.g. `Scan@modules/ftp.go`.
This arose from debugging https://ichnaea.eecs.umich.edu/admin/tasks/a47e2ae2-4f47-4ae4-86da-b8cc3a85a5c9 -- since the code panicked, the IP address did not get written to the output. We don't log the IP in non-panic cases since in those cases, the IP address should be available in the output.
Re https://trello.com/c/CcL2qo60/1191-zgrab-https-scan-segfault, which was fixed by https://github.com/zmap/zcrypto/pull/107.
=> zgrab: log target address/port on panic

zlib/http.go
consistently use http.PageFingerprint for body_sha256, which is marshaled as hex (cc @cdzombak )
=> body_sha256 to hex

ztools/processing/input.go
If it hits a host that returns syntactically-valid response but violates the `json.Marshal` checks, a panic is currently raised, stopping the rest of the scan.
This patch will instead log the error.
=> ztools/processing: marshal errors should not abort scans
